services:
  - type: web
    name: tra_ratings
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd tra_ratings && python -m gunicorn tra_ratings.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ratings_prd_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: tra_ratings.settings
      - key: WEB_CONCURRENCY
        value: 4
